version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    container_name: client-docker
    restart: always
    links:
      - server

  server:
    build: ./server
    ports:
      - '3333:3333'
    container_name: server-docker
    restart: always
    links:
      - db

  db:
    tty: true
    image: keinos/sqlite3:latest
    container_name: database-docker
    restart: always
